<?php

use Illuminate\Database\Seeder;

class DasPendudukTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('das_penduduk')->delete();
        
        \DB::table('das_penduduk')->insert(array (
            0 => 
            array (
                'id' => 1,
                'nama' => 'SAENAH',
                'nik' => '5203097112120003',
                'id_kk' => 1,
                'kk_level' => 1,
                'id_rtm' => 0,
                'rtm_level' => 0,
                'sex' => 2,
                'tempat_lahir' => 'Erot Lauk',
                'tanggal_lahir' => '1912-12-31',
                'agama_id' => 1,
                'pendidikan_kk_id' => 1,
                'pendidikan_id' => 0,
                'pendidikan_sedang_id' => 18,
                'pekerjaan_id' => 19,
                'status_kawin' => 4,
                'warga_negara_id' => 1,
                'dokumen_pasport' => NULL,
                'dokumen_kitas' => NULL,
                'ayah_nik' => '',
                'ibu_nik' => '',
                'nama_ayah' => 'PAPUQ NUH',
                'nama_ibu' => 'PAPUQ NUH',
                'foto' => '',
                'golongan_darah_id' => 0,
                'id_cluster' => 6,
                'status' => 1,
                'alamat_sebelumnya' => '',
                'alamat_sekarang' => '',
                'status_dasar' => 1,
                'hamil' => NULL,
                'cacat_id' => NULL,
                'sakit_menahun_id' => 0,
                'akta_lahir' => '',
                'akta_perkawinan' => '',
                'tanggal_perkawinan' => '0000-00-00',
                'akta_perceraian' => '',
                'tanggal_perceraian' => NULL,
                'cara_kb_id' => NULL,
                'telepon' => NULL,
                'tanggal_akhir_pasport' => '0000-00-00',
                'no_kk_sebelumnya' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'nama' => 'PAPUK RUHAEMAN',
                'nik' => '5203094107200019',
                'id_kk' => 2,
                'kk_level' => 1,
                'id_rtm' => 0,
                'rtm_level' => 0,
                'sex' => 2,
                'tempat_lahir' => 'Lendang Karang',
                'tanggal_lahir' => '1920-07-01',
                'agama_id' => 1,
                'pendidikan_kk_id' => 2,
                'pendidikan_id' => 0,
                'pendidikan_sedang_id' => 18,
                'pekerjaan_id' => 19,
                'status_kawin' => 4,
                'warga_negara_id' => 1,
                'dokumen_pasport' => NULL,
                'dokumen_kitas' => NULL,
                'ayah_nik' => '',
                'ibu_nik' => '',
                'nama_ayah' => 'AMAK RIAMAH',
                'nama_ibu' => 'INAK RIAMAH',
                'foto' => '',
                'golongan_darah_id' => 0,
                'id_cluster' => 12,
                'status' => 1,
                'alamat_sebelumnya' => '',
                'alamat_sekarang' => '',
                'status_dasar' => 1,
                'hamil' => NULL,
                'cacat_id' => NULL,
                'sakit_menahun_id' => 0,
                'akta_lahir' => '',
                'akta_perkawinan' => '',
                'tanggal_perkawinan' => '0000-00-00',
                'akta_perceraian' => '',
                'tanggal_perceraian' => NULL,
                'cara_kb_id' => NULL,
                'telepon' => NULL,
                'tanggal_akhir_pasport' => '0000-00-00',
                'no_kk_sebelumnya' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'nama' => 'MINAH',
                'nik' => '5203094107200020',
                'id_kk' => 3,
                'kk_level' => 1,
                'id_rtm' => 0,
                'rtm_level' => 0,
                'sex' => 2,
                'tempat_lahir' => 'Erot Daya',
                'tanggal_lahir' => '1920-07-01',
                'agama_id' => 1,
                'pendidikan_kk_id' => 1,
                'pendidikan_id' => 0,
                'pendidikan_sedang_id' => 18,
                'pekerjaan_id' => 1,
                'status_kawin' => 4,
                'warga_negara_id' => 1,
                'dokumen_pasport' => NULL,
                'dokumen_kitas' => NULL,
                'ayah_nik' => '',
                'ibu_nik' => '',
                'nama_ayah' => 'PP. JUMLAH',
                'nama_ibu' => 'PP. JUMLAH',
                'foto' => '',
                'golongan_darah_id' => 0,
                'id_cluster' => 18,
                'status' => 1,
                'alamat_sebelumnya' => '',
                'alamat_sekarang' => '',
                'status_dasar' => 1,
                'hamil' => NULL,
                'cacat_id' => NULL,
                'sakit_menahun_id' => 0,
                'akta_lahir' => '',
                'akta_perkawinan' => '',
                'tanggal_perkawinan' => '0000-00-00',
                'akta_perceraian' => '',
                'tanggal_perceraian' => NULL,
                'cara_kb_id' => NULL,
                'telepon' => NULL,
                'tanggal_akhir_pasport' => '0000-00-00',
                'no_kk_sebelumnya' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'nama' => 'AMAQ RAEHAN',
                'nik' => '5203093112200001',
                'id_kk' => 4,
                'kk_level' => 1,
                'id_rtm' => 0,
                'rtm_level' => 0,
                'sex' => 1,
                'tempat_lahir' => 'Lendang Karang',
                'tanggal_lahir' => '1920-12-31',
                'agama_id' => 1,
                'pendidikan_kk_id' => 1,
                'pendidikan_id' => 0,
                'pendidikan_sedang_id' => 18,
                'pekerjaan_id' => 9,
                'status_kawin' => 4,
                'warga_negara_id' => 1,
                'dokumen_pasport' => NULL,
                'dokumen_kitas' => NULL,
                'ayah_nik' => '',
                'ibu_nik' => '',
                'nama_ayah' => 'AMAQ SAAD',
                'nama_ibu' => 'INAQ SAAD',
                'foto' => '',
                'golongan_darah_id' => 0,
                'id_cluster' => 12,
                'status' => 1,
                'alamat_sebelumnya' => '',
                'alamat_sekarang' => '',
                'status_dasar' => 1,
                'hamil' => NULL,
                'cacat_id' => NULL,
                'sakit_menahun_id' => 0,
                'akta_lahir' => '',
                'akta_perkawinan' => '',
                'tanggal_perkawinan' => '0000-00-00',
                'akta_perceraian' => '',
                'tanggal_perceraian' => NULL,
                'cara_kb_id' => NULL,
                'telepon' => NULL,
                'tanggal_akhir_pasport' => '0000-00-00',
                'no_kk_sebelumnya' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'nama' => 'PP. AHYAR',
                'nik' => '5203097112220004',
                'id_kk' => 5,
                'kk_level' => 1,
                'id_rtm' => 0,
                'rtm_level' => 0,
                'sex' => 2,
                'tempat_lahir' => 'Erot Lauk',
                'tanggal_lahir' => '1922-12-31',
                'agama_id' => 1,
                'pendidikan_kk_id' => 2,
                'pendidikan_id' => 0,
                'pendidikan_sedang_id' => 18,
                'pekerjaan_id' => 19,
                'status_kawin' => 4,
                'warga_negara_id' => 1,
                'dokumen_pasport' => NULL,
                'dokumen_kitas' => NULL,
                'ayah_nik' => '',
                'ibu_nik' => '',
                'nama_ayah' => 'PP. NUH',
                'nama_ibu' => 'PP. NUH',
                'foto' => '',
                'golongan_darah_id' => 0,
                'id_cluster' => 6,
                'status' => 1,
                'alamat_sebelumnya' => '',
                'alamat_sekarang' => '',
                'status_dasar' => 1,
                'hamil' => NULL,
                'cacat_id' => NULL,
                'sakit_menahun_id' => 0,
                'akta_lahir' => '',
                'akta_perkawinan' => '',
                'tanggal_perkawinan' => '0000-00-00',
                'akta_perceraian' => '',
                'tanggal_perceraian' => NULL,
                'cara_kb_id' => NULL,
                'telepon' => NULL,
                'tanggal_akhir_pasport' => '0000-00-00',
                'no_kk_sebelumnya' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
        ));
        
        
    }
}